apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - mooncake-master.yaml
  - mooncake-config.yaml

labels:
  - pairs:
      llm-d.ai/subguide: pd-disaggregation-mooncake
    includeSelectors: false
    includeTemplates: false
    fields:
      - group: apps
        version: v1
        kind: Deployment
        path: metadata/labels
        create: true

patches:
  - path: patch-decode.yaml
  - path: patch-prefill.yaml
